# Generated by Django 4.2.3 on 2023-08-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0002_alter_advertisement_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='updated_at',
        ),
    ]
