# Generated by Django 4.2.3 on 2023-08-07 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0005_advertisement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
    ]
