# Generated by Django 4.2.3 on 2023-08-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisement', '0009_advertisement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='user',
        ),
    ]
